import Head from 'next/head';
import ShowCase from '../components/ShowCase';

export default function Home() {
  return (
    <>
      {/* App Wrapper */}
      <div className="h-full w-full flex flex-col">
        <Head>
          <title>Nexon | Live for Road Trips</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.ico" />
        </Head>
        <ShowCase />
      </div>
    </>
  );
}
